server:
  port: 7101

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/rabbitmq-dist-transaction?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: xuxing2019.
  rabbitmq:
    host: rabbit.com
    port: 5672
    virtual-host: /xuxingstudy
    username: admin
    password: admin
