server:
  port: 7001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vm:3306/rabbitmq-dist-transaction?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: xuxing2019.
  rabbitmq:
    host: rabbit.com
    port: 5672
    virtual-host: /xuxingstudy
    username: admin
    password: admin
    ## NONE值是禁用发布确认模式，是默认值
    ## CORRELATED值是发布消息成功到交换器后会触发回调方法
    ## SIMPLE值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: correlated
    publisher-returns: true
